---
trust-domain: "ap"
task-priority: low

taskgraph:
  cached-task-prefix: "ap.v2.image-updater"
  repositories:
    image_updater:
      name: "image-updater"

  register: eije_taskgraph:register

workers:
  aliases: {}
