---
trust-domain: "ap"
task-priority: low

taskgraph:
  cached-task-prefix: "ap.v2.image-updater"
  repositories:
    image_updater:
      name: "image-updater"

workers:
  aliases:
    linux-small:
      provisioner: ap
      implementation: docker-worker
      os: linux
      worker-type: linux-small
    linux-medium:
      provisioner: ap
      implementation: docker-worker
      os: linux
      worker-type: linux-medium
    images:
      provisioner: ap
      implementation: docker-worker
      os: linux
      worker-type: linux-medium
